### ISSUE TITLE
ints with default 0 or 1 are parsed wrong.

### ISSUE THREAD

**Issue by bj0** [jamesob/clii#2]
I really like how small and simple this lib is, thanks for making it!

I've been playing with it for a little bit and I noticed that when I define an integer argument with a default of `1` or `0`, it gets turned into a boolean flag.

I tracked it down to the check:
```if self.type == bool or self.default in [True, False]:```

Apparently `1 in [True, False]` is True....

**Comment by jamesob** [comment]
Thanks for the report @bj0 and glad you're enjoying the library.
