### ISSUE TITLE
new version (0.2.2) does not import.

### ISSUE THREAD

**Issue by bj0** [jamesob/clii#4]
Using poetry to create a fresh virtualenv and installing clii, I am unable to import it.  pip even lists it as installed.

```
$ mkdir test
$ cd test
$ poetry init
...
$ poetry add clii
$ poetry shell
$ pip list
Package    Version
---------- -------
clii       0.2.2  
pip        19.2.3 
setuptools 41.2.0 
$ python
>>> import clii
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'clii'
```

This works fine with 0.2.1

**Comment by jamesob** [comment]
Oof, that's bad. Thanks for the heads-up and sorry for the delay - fixing now.

**Comment by jamesob** [comment]
Fixed; thanks for the report and my apologies.
