### ISSUE TITLE
default command.

### ISSUE THREAD

**Issue by bj0** [jamesob/clii#5]
I find my most common use case (previously with click) was to add cli options to a single-command script.  Is it possible to make clii run a default command (or the only existing command)?  That way you don't have to type "python main.py main --args" to run your main function.

**Comment by jamesob** [comment]
Does [the `main` decorator](https://github.com/jamesob/clii/blob/master/clii.py#L191) not do the trick for you?

**Comment by bj0** [comment]
Oh, I didn't know about that one, thanks!
